### ISSUE TITLE
iOS/iPadOS 13 Beta issues - (discussion)

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#680] opened 2019-06-25 00:16 UTC
Thought it might be worth having a thread on issues people have seen with IOS 13. One I've come across atm is that the grouping of sprinkers/valves etc dont show any zone labels and the controls are large. 

![IMG_0038](https://user-images.githubusercontent.com/19759130/60060025-3384a200-9732-11e9-87c1-1087fc57a1b2.png)

**Comment by aboulfad** [comment] 2019-06-25 21:13
That will most likely be addressed in later betas. What I also stumbled on, is that in ios13 public beta 1, if you have a service with subtypes, all created accessories are grouped under the fist service(no LinkedServices used) which isn't the case in ios 12.x

So the same HAP-Node script yields different representations... I know that Homebridge doesn't have this problem but can't figure out why!

```javascript
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var uuid = require('../').uuid;

var accUUID = uuid.generate('hap-nodejs:accessories:' +'test');
var acc = exports.accessory = new Accessory(p1 + p2, accUUID);
acc.username = "11:22:33:44:55:02";
acc.pincode = "031-45-102";

var sszones = [
  ['Salon Motion Sensor', 'MotionSensor'],
  ['Patio Door', 'ContactSensor']
];
  
//add services
for (const [i, v] of sszones.entries()) {

  instance[i] = new Service[v[1]](v[0],v[0]);
  acc.addService(instance[i]);
}
```

**iOS 12.x**

<img src="https://user-images.githubusercontent.com/16640625/60132843-5763da00-976a-11e9-9abc-b638dc793439.jpeg" width="300">

**iOS 13**
<img src="https://user-images.githubusercontent.com/16640625/60132885-6480c900-976a-11e9-8208-8a0864ade7a6.PNG" width="300" align="center">
<img src="https://user-images.githubusercontent.com/16640625/60132891-677bb980-976a-11e9-8fff-1058ca666d4f.PNG" width="300">

**Comment by n0rt0nthec4t** [comment] 2019-06-25 23:02
Yep, saw that with my home developed irrigation system which has a power switch linked to teh irrigation system accessory.. iOS 13 shows these grouped together

**Comment by aboulfad** [comment] 2019-06-25 23:05
It's pretty annoying, because now its one additional click to view/control accessories, and as you mentioned icons are large ...I am trying to understand what Homebridge does such that even with ios13, all accessories show separate and not grouped. But it's hard...

**Comment by n0rt0nthec4t** [comment] 2019-06-25 23:06
submit feedback on the issue, as I have done

**Comment by aboulfad** [comment] 2019-06-25 23:47
ok found another difference explaining why HB survives the iOS 13 change:

1- It's a bridge, as such all accessories need to have `this.bridged = true`
2- It does create a `UUID` per accessory
3- no use of subtypes

I will try using HAP-Node` BridgedCore` and implement these changes, then I'll try using `Core`. Probably has to do with `subtypes`, something must have changed in ios 13 where multiple services per UUID using `subtypes` are now grouped together.

**Comment by tobekas** [comment] 2019-06-26 17:57
No not mix accessories and services. In iOS13 Apple will group multiple services used in one accessory. If you expose only one accessory with multiple service, they will be grouped. I think same for Homebridge if you add multiple services to one bridged accessory. But as long as Homebridge exposes multiple bridged accessories(!) with their own services, they will not be grouped in iOS13.

**Comment by aboulfad** [comment] 2019-06-26 18:09
> No not mix accessories and services. In iOS13 Apple will group multiple services used in one accessory. If you expose only one accessory with multiple service, they will be grouped. 

Yes, thats what we noticed. It was a convenient way to group different services under one accessory, but now we gotta change that for iOS13.

>I think same for Homebridge if you add multiple services to one bridged accessory. But as long as Homebridge exposes multiple bridged accessories(!) with their own services, they will not be grouped in iOS13.

Yep, confirmed using HB/iOS13. So I've been trying to understand what and how HB does what it does, and I got most of it, except I can't replicate it outside of HB, i.e. using `node BridgedCore`. For some reason, only the last accessory is exposed/added ...

**Comment by tobekas** [comment] 2019-06-26 19:03
Ok. I can’t help you with these implementation details.
But it is absolutely advantageous to use the bridge concept, because otherwise you would have to add each single accessory separately with its own setup code...
In addition, bridges accessories can even be added or removed live.

**Comment by aboulfad** [comment] 2019-06-26 19:11
> Ok. I can’t help you with these implementation details.

Thank you, I'll eventually figure it out !

> But it is absolutely advantageous to use the bridge concept, because otherwise you would have to add each single accessory separately with its own setup code...
> In addition, bridges accessories can even be added or removed live.

Up until now, I had limited amount of accessories using HAP-Node (10), and used the `subtype` to group multiple services under one acc with one setup code. But iOS13 changed this as we see above, so yeah `bridge` it is :)

**Comment by n0rt0nthec4t** [comment] 2019-10-02 22:49
As noted on MacRumors around iOS/iPadOS 13.2 beta 1, you can now seperate tiles out

> HomeKit Grouping - In the HomeKit app, there's a new option to group or ungroup accessories that have multiple functions, showing them either as a single tile or as multiple tiles. Multiple tiles was the pre-iOS 13 default, while Single Tile is the iOS 13 default. 
> 
> ![](https://cdn.macrumors.com/article-new/2019/10/homekitoptions.jpg)

**Comment by NorthernMan54** [comment] 2019-10-02 22:52
Anything around the dropping of photo notifications from having contact/motion sensors in the same room as a camera?

**Comment by n0rt0nthec4t** [comment] 2019-10-02 23:00
I dont have any contact/motion sensors for a camera (yet) :-). Have to get the public beta installed and try some things out. But glad this option is now present

**Closed** 2020-04-08 21:13 UTC
