### ISSUE TITLE
LockMechanism doesn't work with Siri ?

### ISSUE THREAD

**Issue by Supergiovane** [homebridge/HAP-NodeJS#776] opened 2020-01-14 09:29 UTC
### First of all, thank you for this great node!

I'm using this wrapped into node-red-contrib-homekit-bridged node.
Don't know if it's an issue with HAP-NodeJS or with node-red-contrib-homekit-bridged (i already opened an issue on node-red-contrib-homekit-bridged), but is there someone that can do a quick test for me?

The LockMechanism doesn't work with commands issued by my voice to Siri. Using the home app, it works instead.

**To reproduce**
Create a "main door" device set to Lockmechanism.
Try open the "main door" from Siri (Hey siri, open the main door).
**Expected behaviour**
The door should open, but instead, siri tells me "i'm still opening the door, ask me later if the door is open", and nothing happens.
If i open the door by tapping the icon in the Home App, the node emits a message to the flow and the door opens.

Thank you.

**Comment by Shaquu** [comment] 2020-01-14 12:08
NRCHKB/node-red-contrib-homekit-bridged#190

**Comment by Supereg** [comment] 2020-01-14 20:39
This could be related to #770/#769, depending on how the lock service is implemented.
This is just a big maybe, but you should check, that the latest version (v0.5.5) of hap-nodejs is used. If you do not find any other reason for this behavior this could very well be the cause.

**Comment by Supereg** [comment] 2020-04-08 21:08
Any news on this? Issue still persist with the latest hap-nodejs update?

**Comment by Supereg** [comment] 2020-04-13 14:35
Closing this as it seems to be resolved.

**Closed by Supereg** 2020-04-13 14:35 UTC
