### ISSUE TITLE
How does HKSV determine if camera on/offline???

### ISSUE THREAD

**Issue by n0rt0nthec4t** [homebridge/HAP-NodeJS#1074] opened 2024-10-02 03:16 UTC
### Current Situation

Wondering how HomeKit determines in a camera is online or offline? Been having very very random issues where HomeKit says 'x camera is offline' etc, so wondering what really needs to set? Camera's dont appear to have an Active characteristic, and can only see from the HKSV spec that the motion sensor needs to have this

### Logs

```markdown
..
```

### Configuration

```json
..
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by hjdhjd** [comment] 2024-10-02 05:30
HKSV doesn’t. HomeKit does. The issues you’re referencing are likely due to as-yet-not-fully-resolved issues with mDNS and HomeKit. If the issue you’re referencing is the inevitable Home app message around cameras going offline and returning…that’s the root cause. Why/how/etc…you’re welcome to troubleshoot, but it’s inconsistent enough to have eluded effective troubleshooting for years. Definitely far more rare an issue when using Avahi than Bonjour-HAP or ciao, however.

**Comment by n0rt0nthec4t** [comment] 2024-10-02 07:27
Yep, thats the issue have seen, but has definitely become "more common" recently.  Seems to occur (subjectively) when this issue which ciao occurs https://github.com/homebridge/ciao/issues/50 but been no movement on the maintainers to look at that one

**Comment by hjdhjd** [comment] 2024-10-02 11:34
Since I’ve one of the maintainers, this constitutes movement. 😄 I’m going to close this issue in favor of the one above.

**Closed as completed by hjdhjd** 2024-10-02 11:34 UTC
Labels: question
