### ISSUE TITLE
Unable to reach accessory 

### ISSUE THREAD

**Issue by mrpinkcat** [homebridge/HAP-NodeJS#840] opened 2020-08-07 02:30 UTC
Hi,

I want to use the new npm module but when i copy paste the light example, my iphone "can't reach the accessory". Nothing in the console. I'm running ISO 14 Beta 3 developer.

**Comment by Shaquu** [comment] 2020-08-09 18:09
Hi, I think you should start with some details.
Which OS are you using, which versions of NodeJS etc.

**Comment by mrpinkcat** [comment] 2020-08-13 03:12
Hi, i'm using MacOS 10.15 with node 12.18.3.

The beta branch work fine and remove the error.

**Comment by mrpinkcat** [comment] 2020-08-13 03:15
> I'm running ISO 14 Beta 3 developer.

I try to paired the light with my friend phone running the latest stable version of iOS 13 but this didn't work too.

**Comment by Supereg** [comment] 2020-09-14 18:09
You mentioned that the beta resolved the issue? Is that correct?
v0.8.0 is now released (previously in beta), does your issue still persist?

**Comment by mrpinkcat** [comment] 2020-09-15 13:29
Now the accessory is not visible in the list of iphone when i try to add it. Even if i fork your example of lightbulb :/
It not appear even when i type the pincode.

**Comment by Supereg** [comment] 2020-09-16 02:23
Would be great if you could try the latest v0.8.2 release

**Comment by n0rt0nthec4t** [comment] 2020-09-30 06:41
@Supereg not sure if related to 0.8.2 or the ciao model replacing bonjour, but since an upgrade of one of my accessories yesterday which was running 0.5.11 to 0.8.2, now getting these errors randomly in the logs:

Sep 30 13:42:15 garagedoor node[4481]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Sep 30 13:42:15 garagedoor node[4481]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)

**Comment by Supereg** [comment] 2020-10-12 17:00
@n0rt0nthec4t is this still happening? If yes could you provide the nodejs version running.

**Comment by n0rt0nthec4t** [comment] 2020-10-12 22:18
> @n0rt0nthec4t is this still happening? If yes could you provide the nodejs version running.

Yes, still random

Oct 08 10:35:26 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 08 10:35:26 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)
Oct 08 10:35:29 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 08 10:35:29 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)

pi@garagedoor:~/HAP-NodeJS/dist $ node -v
v11.15.0

This is the last "officially"support version of nodejs for a raspberry pi zero as I understand it

**Comment by Supereg** [comment] 2020-10-12 22:26
First of all, this error shouldn't really impact operation (or does it?).

node v11 is no longer maintained by the nodejs folks (see https://nodejs.org/en/about/releases/). Would you mind upgrading to node 12 or any other node version listed in the supplied link, which still receives maintenance updates.

**Comment by n0rt0nthec4t** [comment] 2020-10-12 22:30
Doesn't appear to effect things, but as stated, you cannot upgrade past nodejs 11.x on a raspberry pi zero as there is no supported build available for it

**Comment by Supereg** [comment] 2020-10-12 22:46
The maybe move to node v10 or try the v12 unofficial build at https://unofficial-builds.nodejs.org/download/release/v12.19.0/ (also installable via `hb-service update-node`; disclaimer regarding unofficial builds: https://github.com/nodejs/unofficial-builds).

My current assumption is that this is not directly caused by hap-nodejs/ciao itself, as `EINVAL` would suggest, that we have passed some sort of illegal argument, which is not the case, judging by the printed error and an overall code analysis.

**Comment by n0rt0nthec4t** [comment] 2020-10-12 22:54
So why you would move back a version ie: 11 -> 10, given both are unsupported as stated ? ;-). I've tried the "unofficial" builds, but they have issues with the RPIO package.

**Comment by Supereg** [comment] 2020-10-12 23:06
@NorthernMan54 v10 is a LTS (long term support) version which reaches end of life on `2021-04-30` thus is still actively patched, whereas node v11 reached end of life on `2019-06-01` (with the last version released on `2019-04-30`) (here is a full overview https://endoflife.software/programming-languages/server-side-scripting/nodejs).
So in this situation v10 may have less language features, but will receive bug fixes and security updates much longer.

**Comment by n0rt0nthec4t** [comment] 2020-10-22 00:10
So tried LTS version of node, and the error still persists. Its definitely a change since backend migrated from bonjour to ciao 

Oct 19 13:29:25 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 19 13:29:25 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)
Oct 19 13:34:12 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 19 13:34:12 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)
Oct 19 13:34:51 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 19 13:34:51 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)
Oct 19 13:34:54 garagedoor node[27497]: Encountered MDNS socket error on socket 'wlan0' : Error: send EINVAL 224.0.0.251:5353
Oct 19 13:34:54 garagedoor node[27497]:     at SendWrap.afterSend [as oncomplete] (dgram.js:526:11)

**Comment by Supereg** [comment] 2020-11-11 00:40
@NorthernMan54 Does the error affect operation at all? Are your devices still able to find the homebridge/hap-nodejs instance?

**Comment by Supereg** [comment] 2020-11-14 19:00
Closing the issue as OP couldn't provide enough information to debug this.

**Comment by Supereg** [comment] 2020-11-29 22:03
For anyone else, you might want to try the latest 0.9.0 beta, which adds some more stability to mdns.

**Closed** 2020-11-29 22:02 UTC
Labels: bug
