### ISSUE TITLE
Incorrect handling of cvoId in RTPStreamManagement - pulling my hair out!

### ISSUE THREAD

**Issue by adriancable** [homebridge/HAP-NodeJS#905] opened 2021-09-02 08:42 UTC
I need to use the CVO_ENABLED feature for my application. (I believe it's the only way to get 3:4 aspect ratio video.) (Everything is fine on the video source (RTP) side regarding setting the CVO setting in the RTP header extensions etc.)

On the HAP-NodeJS, even if I set cvoId in streamingOptions when creating the camera controller, when the stream starts, CVO doesn't actually get enabled, and cvoId is 'undefined' in the handleStreamRequest callback.

I looked through RTPStreamManagement.ts and compared with Apple's public HomeKit spec docs, and first there seems to be a mistake:

const enum VideoCodecCVO { // Coordination of Video Orientation
  UNSUPPORTED = 0x01,
  SUPPORTED = 0x02
}

should be:

const enum VideoCodecCVO { // Coordination of Video Orientation
  UNSUPPORTED = 0x00,
  SUPPORTED = 0x01
}

However, even with this fixed it still doesn't work. CVO_ENABLED should be index #4 in the videoParametersTLV that _handleStartStream digests. However, at least for me, index #4 is always totally absent in the videoParametersTLV when _handleStartStream is called.

CVO definitely should work on the HomeKit side: the Logitech Circle View uses it. Any ideas much appreciated as I really am pulling my hair out over this. @KhaosT ? @koush ? @sunoo ?

**Comment by adriancable** [comment] 2021-09-03 05:46
Update: I found out why 3:4 video the 'normal' way didn't work - it is due to some behaviour with libx264's sliced threading encoder when images are taller than they are wide which HomeKit doesn't like. Switching to frame threading fixed it. (A little bizarre, but true.) Still interested in understanding why CVO doesn't work in HAP-NodeJS, but no longer worth most people spending too much time thinking about it.

**Comment by Supereg** [comment] 2021-09-03 06:38
Though your particular issue is fixed, would keep the issue open to keep a reference for the CVO thingy.

**Comment by Supereg** [comment] 2021-11-05 19:19
Okay, so I finally fixed the values of the `VideoCodecCVO` enum.

> However, even with this fixed it still doesn't work. CVO_ENABLED should be index #4 in the videoParametersTLV that _handleStartStream digests. However, at least for me, index #4 is always totally absent in the videoParametersTLV when _handleStartStream is called.

I couldn't quite find an explanation for where this issue might stem from. However, don't really have anything to test CVO. I made however a fix to the `RTPStreamManagement` which could in special circumstances (when you restore a Camera accessory from disk, somewhat common with homebridge plugins) prevent updated streaming options to be reflected in the according characteristics: https://github.com/homebridge/HAP-NodeJS/commit/25a0eaae0d1a354832f1dbb326ccff87f6a41b7a. Maybe that was the root cause?

Anyway, would be happy if you could further investigate the issue and check if that maybe indeed solved the problem.

**Comment by adriancable** [comment] 2021-11-05 21:03
Hi @Supereg - thanks for fixing the enum. In my tests, I wasn't restoring an accessory from disk. I was recreating from scratch each time and deleting the AccessoryInfo and IdentifierCache each time between trials (to avoid any cacheing/persistent state issues).

Maybe CVO has been deprecated/removed in a recent version of iOS?

**Comment by Supereg** [comment] 2021-11-05 21:10
> Maybe CVO has been deprecated/removed in a recent version of iOS?

Not sure if that's it. I always though it was actually never implemented by the Home App. But you said the Logitech Cam supports/supported it?
At least I couldn't find anything odd from a static analysis POV why this feature shouldn't work from the hap-nodejs side. But as I said, I don't have anything to test here.

**Comment by Supereg** [comment] 2021-11-09 18:25
The `VideoCodecCVO` enum misaligned and the above-described issue with disk-restored accessories was fixed in the latest v0.9.7 release.

I couldn't find any further indication why the CVO thingy wouldn't work. Feel free to reopen the issue if you encounter any further issues.

Thanks :)

**Closed by Supereg** 2021-11-09 18:25 UTC
Labels: bug
